<?php

namespace App\Annotation;

use Hyperf\Di\Annotation\AbstractAnnotation;
use Hyperf\Di\Annotation\AnnotationInterface;
use PHPMD\Node\Annotation;


/**
 * @Annotation
 * @Target({"CLASS","METHOD"})
 */
class Foo extends AbstractAnnotation
{
    /**
     * @var string
     */
    public $bar;

    public function __construct($value = null)
    {
        parent::__construct($value);
//        AnnotationInterface::
        $this->bindMainProperty('bar', $value);
    }

    public function collectClass(string $className): void
    {
        parent::collectClass($className); // TODO: Change the autogenerated stub
    }

}